<?php
function number_block_theme()
{
    return array_merge(drupal_common_theme(), [
        'block__number_block' => [
            'render element' => 'elements',
            'base hook' => 'block',
        ],
    ]);
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function number_block_preprocess_block(&$variables)
{

}

function number_block_preprocess_block__number_block(&$variables)
{
    $variables['#attached']['library'] = 'number_block/number';
}
