<?php
namespace Drupal\domynic_view\Plugin\views\field;

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Plugin\views\field\FieldPluginBase;
use Drupal\views\ResultRow;

/**
 * @ingroup views_field_handlers
 *
 * @ViewsField("domynic_view_content")
 */
class DomynicViewContent extends FieldPluginBase
{
    public function query()
    {

    }

    protected function defineOptions()
    {
        $options = parent::defineOptions(); // TODO: Change the autogenerated stub
        $options['domynic_view_content'] = ['default' => ''];
        return $options;
    }

    public function buildOptionsForm(&$form, FormStateInterface $form_state)
    {
        $form['domynic_view_content'] = [
            '#title' => t('Domynic view content'),
            '#description' => t('description domynic view'),
            '#default_value' => $this->options['domynic_view_content'],
            '#type' => 'textarea',
            '#required' => TRUE
        ];
        parent::buildOptionsForm($form, $form_state); // TODO: Change the autogenerated stub
    }

    public function render(ResultRow $values)
    {
        $views = "";
        if (!empty($this->view->field['domynic_view_content'])) {
            $views = $this->view->field['domynic_view_content']->options['domynic_view_content'];
        }
        return ['#markup' => $views];
    }

    public function clickSort($order)
    {
        $this->query->addOrderBy('domynic_view_content', 'created', $order);
    }

}