<?php
use Drupal\Core\Form\FormStateInterface;


function domynic_theme()
{
    return [
        'domynic_view' => [
            'variables' => ['nodes' => null],
        ],
        'domynic_view_detail' => [
            'variables' => ['node' => null],
        ],
    ];
}


/**
 * Implements hook_form_alter().
 */
function domynic_form_alter (&$form, FormStateInterface $form_state, $form_id)
{
    if ($form_id === 'node_domynic_form') {
        $form['#attached']['library'][] = 'domynic/domynic';
        $form['#validate'][] = 'domynic_form_node_validate';
    }


}

function domynic_form_node_validate ($form, FormStateInterface $form_state)
{

    if ($form_state->hasValue('field_birth')) {
        $birth = $form_state->getValue('field_birth');
        $date = strtotime($birth[0]['value']->format('Y-m-d'));
        $current_date = strtotime(date('Y-m-d'));
        if ($date > $current_date || $date == $current_date) {
            $form_state->setErrorByName('field_birth', 'Please enter the birthday date');
        }
    }

    if ($form_state->hasValue('field_slug')) {
        $text_slug = $form_state->getValue('field_slug');
        $query = \Drupal::entityQuery('node');
        $query->condition('status',1);
        $query->condition('type','domynic');
        $query->condition('field_slug', $text_slug[0]['value']);
        $nid = $query->execute();
        if ($nid) {
            $form_state->setErrorByName('field_slug', 'Slug existed!');
        }
    }
}


