<?php
function about_block_theme()
{
    return array_merge(drupal_common_theme(), [
        'block__about_block' => [
            'render element' => 'elements',
            'base hook' => 'block',
        ],
    ]);
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function about_block_preprocess_block(&$variables)
{
    $variables['nodes'] = '';
    if ($variables['content']['nodes']['#access'] && $variables['content']['nodes']['#markup']) {
        $variables['nodes'] = $variables['content']['nodes']['#markup'];
    }
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function about_block_preprocess_block__about_block(&$variables)
{
    $variables['#attached']['library'] = 'about_block/about_block';
}
