<?php
function social_block_theme()
{
    return array_merge(drupal_common_theme(), [
        'block__social_block' => [
            'render element' => 'elements',
            'base hook' => 'block',
        ],
    ]);
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function social_block_preprocess_block(&$variables)
{
    $variables['social_list'] = '';
    if ($variables['content']['social_list']['#access'] && $variables['content']['social_list']['#markup']) {
        $variables['social_list'] = $variables['content']['social_list']['#markup'];
    }
}

function social_block_preprocess_block__social_block(&$variables)
{

        $variables['#attached']['library'] = 'social_block/social_block';
}

