<?php
function portfolio_theme()
{
    return array_merge(drupal_common_theme(), [
        'block__about_block' => [
            'render element' => 'elements',
            'base hook' => 'block',
        ],
    ]);
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function portfolio_preprocess_block(&$variables)
{
    $variables['cates'] = '';
    if ($variables['content']['cates']['#access'] && $variables['content']['cates']['#markup']) {
        $variables['cates'] = $variables['content']['cates']['#markup'];
    }

    $variables['limit'] = '';
    if ($variables['content']['cate_limit']['#access'] && $variables['content']['cate_limit']['#markup']) {
        $variables['limit'] = $variables['content']['cate_limit']['#markup'];
    }

}


/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function portfolio_preprocess_block__portfolio(&$variables)
{
    $variables['#attached']['library'][] = 'portfolio/portfolio';
}
