<?php
function menu_block_theme()
{
    return array_merge(drupal_common_theme(), [
        'block__menu_block' => [
            'render element' => 'elements',
            'base hook' => 'block',
        ],
    ]);
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function menu_block_preprocess_block(&$variables)
{
    $variables['menus'] = '';
    if ($variables['content']['menu']['#access'] && $variables['content']['menu']['#markup']) {
        $variables['menus'] = $variables['content']['menu']['#markup'];
    }
}


/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function menu_block_preprocess_block__menu_block(&$variables)
{
    $variables['#attached']['library'][] = 'menu_block/menu_block';


}
